michelboaventura/mj_data_explorer

app/jobs/perform_job.rb
Cria um novo método no processamento que gera um json que será utilizadopara a busca textual dos resultados.
=> Gera json para a busca dos resultados

frontend/app/components/visualizations/search-tool.js, frontend/app/index.html, frontend/app/styles/app.scss, frontend/app/styles/mixins.scss, frontend/app/styles/visualizations/graph-canvas/main.scss, frontend/app/styles/visualizations/search-tool/main.scss, frontend/app/templates/components/visualizations/graph-canvas-full.hbs, frontend/app/templates/components/visualizations/graph-canvas.hbs, frontend/app/templates/components/visualizations/search-tool.hbs, frontend/public/assets/js/gViz/visualizations/graph-canvas/_init.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/bind.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/create.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/drag.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/initialize.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/search.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/setup.js
1 - Implemented search on graph canvas visualization.
2 - Copied to graph canvas full template.
=> Implemented search on graph canvas visualization.

frontend/app/index.html, frontend/app/styles/visualizations/graph-canvas/main.scss, frontend/app/templates/components/visualizations/graph-canvas-full.hbs, frontend/app/templates/components/visualizations/graph-canvas.hbs, frontend/public/assets/js/gViz/visualizations/graph-canvas/_init.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/initialize.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/label.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/setup.js
Adding labels for group colors and centered nodes to graph canvas and graph canvas full visualizations.
=> Adding labels to graph canvas.

frontend/public/assets/js/gViz/visualizations/wordtree/data_.js, frontend/public/assets/js/gViz/visualizations/wordtree/helpers.js, frontend/public/assets/js/gViz/visualizations/wordtree/setup.js
Wordtree diagram: fix root problem for single and multiple children.
=> Wordtree diagram: fix root problem.

frontend/app/components/forms/form-filter.js
=> Utilizar os nomes dos operadores lógicos

frontend/app/routes/datasource/edit.js, frontend/app/templates/datasource/edit.hbs
Component datasource form was delted, but in edit page was calling it.
this closes issue #36
=> Fix error in datasource/edit

.gitignore, app/controllers/json_controller.rb, app/jobs/perform_job.rb, config/application.rb, config/deploy.rb, config/routes.rb
Agora as bases não ficam mais no public e sempre passam pelo rails. Precisamos disso para questões de permissionamento dos arquivos.
=> Passa JSON pelo rails

algorithms/part_item/part_item.rb
=> Corrige legenda do gráfico part x item

app/serializers/job_serializer.rb, frontend/app/components/jobs/large-table.js, frontend/app/routes/consults.js, frontend/app/templates/components/jobs/large-table.hbs, frontend/app/templates/consults.hbs, frontend/tests/integration/components/jobs/large-table-test.js
ordenados por ordem de criação #51
=> Fix sort dos jobs

frontend/app/controllers/job/new.js, frontend/app/templates/job/new.hbs, frontend/tests/unit/controllers/job/new-test.js
=> fix o alerta ao selecionar a base

app/controllers/passwords_controller.rb, config/environments/development.rb, config/environments/production.rb, config/environments/staging.rb, config/routes.rb, frontend/app/controllers/password/edit.js, frontend/app/controllers/password/request.js, frontend/config/environment.js
Em produção e staging ainda é necessário criar um servidor smtp para o envio da senha.
=> Corrige recuperação de senha

frontend/public/assets/js/gViz/visualizations/graph-canvas/search.js
- Fix issue #60: Visualização: Termo sugerido no campo de sugestão não é ativado no grafo por mouse.
- Fix issue #50: Visualização: Corrigir o tipo de match dos termos sugeridos no grafo de co-ocorrencia.
=> Gf graph canvas fixes

frontend/public/assets/js/gViz/visualizations/matrix-chart/draw.js
Labels das matrizes haviam sumido.
=> Conserta label das matrizes

frontend/app/components/visualizations/correlation-matrix.js, frontend/app/components/visualizations/sentiment-analysis/sentiment-matrix.js, frontend/app/styles/visualizations/correlation-matrix/main.scss, frontend/app/styles/visualizations/sentiment-analysis/main.scss, frontend/app/templates/components/visualizations/correlation-matrix.hbs, frontend/app/templates/components/visualizations/sentiment-analysis/sentiment-matrix.hbs, frontend/app/templates/components/visualizations/topicos-vis.hbs, frontend/app/templates/components/visualizations/wordtree-diagram.hbs
=> Pb add label

frontend/app/templates/components/visualizations/correlation-matrix.hbs, frontend/app/templates/components/visualizations/sentiment-analysis/sentiment-matrix.hbs, frontend/app/templates/components/visualizations/topicos-vis.hbs, frontend/app/templates/components/visualizations/wordtree-diagram.hbs
Adiciona títulos para as visualizações que estavam com o problema relatado.
Resolve #113
=> Adiciona títulos de algumas visualizações

app/controllers/users_controller.rb, frontend/yarn.lock
erro do usuario nas issues #108 e #109
=> fix issue #108 e #109

frontend/app/templates/ferramenta/sobre.hbs
=> corrige links para documentos

frontend/app/components/visualizations/topicos-vis.js, frontend/app/templates/components/visualizations/topicos-vis.hbs
Ao clicar nas barras dos eixos ou nas palavras o sistema estava redirecionando o usuário para uma URL inválida.
Corrige #116
=> Corrige links na visualização de tópicos

frontend/app/components/visualizations/correlation-matrix.js, frontend/app/components/visualizations/sentiment-analysis/sentiment-matrix.js, frontend/app/styles/visualizations/correlation-matrix/main.scss, frontend/app/styles/visualizations/sentiment-analysis/main.scss, frontend/app/templates/components/visualizations/correlation-matrix.hbs, frontend/app/templates/components/visualizations/sentiment-analysis/sentiment-matrix.hbs, frontend/public/assets/js/gViz/visualizations/matrix-chart/_init.js, frontend/public/assets/js/gViz/visualizations/matrix-chart/create.js, frontend/public/assets/js/gViz/visualizations/matrix-chart/draw.js, frontend/public/assets/js/gViz/visualizations/matrix-chart/initialize.js
=> Conserta posicionamento das matrizes

frontend/app/templates/application.hbs, frontend/public/assets/js/gViz/visualizations/wordtree/initialize.js
=> Fix wordtree words size and remove spinner icon from loading div

frontend/app/styles/visualizations/main.scss, frontend/app/templates/components/visualizations/empty-vis.hbs
=> Conserta componente de visualização vazia.

frontend/app/routes/ferramenta/perfil.js, frontend/app/routes/ferramenta/perfil/index.js, frontend/app/styles/_components/components_menu.scss, frontend/app/styles/app.scss, frontend/app/templates/ferramenta/perfil/index.hbs, frontend/app/templates/landing-page.hbs
=> fix minor issues

frontend/app/components/visualizations/topicos-vis.js, frontend/app/styles/visualizations/topicos-vis/main.scss, frontend/app/templates/components/visualizations/topicos-vis.hbs
Modificações gerais em tópicos vis para facilitar a visualização dos dados.
=> Modificações gerais em tópicos vis

frontend/app/routes/ferramenta/filtros/aberto.js, frontend/app/styles/visualizations/graph-canvas/main.scss, frontend/app/templates/components/visualizations/graph-canvas-full.hbs, frontend/app/templates/components/visualizations/graph-canvas.hbs, frontend/app/templates/components/visualizations/part-item.hbs, frontend/app/templates/components/visualizations/wordtree-diagram.hbs, frontend/public/assets/js/gViz/visualizations/graph-canvas/drag.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/label.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/setup.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/tooltip.js
=> Pb traduz nomes

frontend/app/templates/ferramenta/filtros/resultado.hbs
=> Coloca espaço entre 'Termos buscados' e nome do filtro

app/jobs/coocorrencia_job.rb, frontend/public/assets/js/gViz/visualizations/graph-canvas/_init.js, frontend/public/assets/js/gViz/visualizations/graph-canvas/setup.js
Grafo agora carrega de uma vez, ao invés de utilizar uma animação. Isso melhora a performance. 
Entretanto, o bind("resize") do _init.js foi comentado, porque ele sumia com o grafo, e este só aparecia novamente ao colocar o mouse na tela.
=> Pb static graph
